//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatingApp.Resources.Labels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Properties {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Properties() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatingApp.Resources.Labels.Properties", typeof(Properties).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me:.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About partner:.
        /// </summary>
        public static string AboutPartner {
            get {
                return ResourceManager.GetString("AboutPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcohol drinks:.
        /// </summary>
        public static string Alcohol {
            get {
                return ResourceManager.GetString("Alcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday:.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best part of your body is:.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodyart:.
        /// </summary>
        public static string Bodyart {
            get {
                return ResourceManager.GetString("Bodyart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite books:.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your diet&lt;br/&gt;(choose all that apply).
        /// </summary>
        public static string Diet {
            get {
                return ResourceManager.GetString("Diet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinking:.
        /// </summary>
        public static string Drinking {
            get {
                return ResourceManager.GetString("Drinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smarts:.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnicity:.
        /// </summary>
        public static string Ethnicity {
            get {
                return ResourceManager.GetString("Ethnicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often do you exercise:.
        /// </summary>
        public static string Exercise {
            get {
                return ResourceManager.GetString("Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyes:.
        /// </summary>
        public static string Eyes {
            get {
                return ResourceManager.GetString("Eyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion brands, designers:.
        /// </summary>
        public static string Fashion {
            get {
                return ResourceManager.GetString("Fashion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your favour fashion style:.
        /// </summary>
        public static string FashionStyle {
            get {
                return ResourceManager.GetString("FashionStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best way to spend free time&lt;br/&gt;&lt;i&gt;(select all that apply)&lt;/i&gt;.
        /// </summary>
        public static string FavoriteFreeTime {
            get {
                return ResourceManager.GetString("FavoriteFreeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Figure:.
        /// </summary>
        public static string Figure {
            get {
                return ResourceManager.GetString("Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair color:.
        /// </summary>
        public static string Hair {
            get {
                return ResourceManager.GetString("Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body height:.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobbies:.
        /// </summary>
        public static string Hobbies {
            get {
                return ResourceManager.GetString("Hobbies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interests:.
        /// </summary>
        public static string Interests {
            get {
                return ResourceManager.GetString("Interests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short introduction &lt;br/&gt;
        ///(max 255 words):.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many kids do you have:.
        /// </summary>
        public static string Kids {
            get {
                return ResourceManager.GetString("Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have kids:.
        /// </summary>
        public static string KidsHave {
            get {
                return ResourceManager.GetString("KidsHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want kids:.
        /// </summary>
        public static string KidsWant {
            get {
                return ResourceManager.GetString("KidsWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate your appearance:.
        /// </summary>
        public static string Look {
            get {
                return ResourceManager.GetString("Look", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite films:.
        /// </summary>
        public static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What music do you like:.
        /// </summary>
        public static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Music:.
        /// </summary>
        public static string MusicStuff {
            get {
                return ResourceManager.GetString("MusicStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You and pets:.
        /// </summary>
        public static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession:.
        /// </summary>
        public static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for:.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion:.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary:.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am looking for:.
        /// </summary>
        public static string SeekSex {
            get {
                return ResourceManager.GetString("SeekSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am:.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking:.
        /// </summary>
        public static string Smoking {
            get {
                return ResourceManager.GetString("Smoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What sport do you like:.
        /// </summary>
        public static string Sport {
            get {
                return ResourceManager.GetString("Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Sports:.
        /// </summary>
        public static string SportStuff {
            get {
                return ResourceManager.GetString("SportStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your status:.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of searched partner:.
        /// </summary>
        public static string StatusPartner {
            get {
                return ResourceManager.GetString("StatusPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite TV Programmes.
        /// </summary>
        public static string TVProgrammes {
            get {
                return ResourceManager.GetString("TVProgrammes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
