//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatingApp.Resources.ErrorMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatingApp.Resources.ErrorMessages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must indicate your full birthday to register..
        /// </summary>
        internal static string BirthdayNotSet {
            get {
                return ResourceManager.GetString("BirthdayNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to set city..
        /// </summary>
        internal static string CityNotSet {
            get {
                return ResourceManager.GetString("CityNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select country..
        /// </summary>
        internal static string CountryNotSet {
            get {
                return ResourceManager.GetString("CountryNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to choose at least one option in diet..
        /// </summary>
        internal static string DietNotSet {
            get {
                return ResourceManager.GetString("DietNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to set drinking preferences..
        /// </summary>
        internal static string DrinkingNotSet {
            get {
                return ResourceManager.GetString("DrinkingNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to set education..
        /// </summary>
        internal static string EducationNotSet {
            get {
                return ResourceManager.GetString("EducationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is in use or reserved..
        /// </summary>
        internal static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to set email..
        /// </summary>
        internal static string EmailNotSet {
            get {
                return ResourceManager.GetString("EmailNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid..
        /// </summary>
        internal static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select ethnicity..
        /// </summary>
        internal static string EthnicityNotSet {
            get {
                return ResourceManager.GetString("EthnicityNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose your style..
        /// </summary>
        internal static string FashionStyleNotSet {
            get {
                return ResourceManager.GetString("FashionStyleNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to set figure..
        /// </summary>
        internal static string FigureNotSet {
            get {
                return ResourceManager.GetString("FigureNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free time favorites not set..
        /// </summary>
        internal static string FreeTimeNotSet {
            get {
                return ResourceManager.GetString("FreeTimeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to set your body height..
        /// </summary>
        internal static string HeightNotSet {
            get {
                return ResourceManager.GetString("HeightNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one hobby is not set..
        /// </summary>
        internal static string HobbiesNotSet {
            get {
                return ResourceManager.GetString("HobbiesNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short personal introduction is not set..
        /// </summary>
        internal static string IntroductionNotSet {
            get {
                return ResourceManager.GetString("IntroductionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to set password..
        /// </summary>
        internal static string PasswordNotSet {
            get {
                return ResourceManager.GetString("PasswordNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too long. Max 30 characters..
        /// </summary>
        internal static string PasswordTooLong {
            get {
                return ResourceManager.GetString("PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too short. Min 3 characters..
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select relationship..
        /// </summary>
        internal static string RelationshipNotSet {
            get {
                return ResourceManager.GetString("RelationshipNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion is not set.
        /// </summary>
        internal static string ReligionNotSet {
            get {
                return ResourceManager.GetString("ReligionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select partner&apos;s sex..
        /// </summary>
        internal static string SeekSexNotSet {
            get {
                return ResourceManager.GetString("SeekSexNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select sex..
        /// </summary>
        internal static string SexNotSet {
            get {
                return ResourceManager.GetString("SexNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to set smoking preferences..
        /// </summary>
        internal static string SmokingNotSet {
            get {
                return ResourceManager.GetString("SmokingNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already taken, Please, choose another one..
        /// </summary>
        internal static string UsernameExists {
            get {
                return ResourceManager.GetString("UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to set username..
        /// </summary>
        internal static string UsernameNotSet {
            get {
                return ResourceManager.GetString("UsernameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is not valid, Please use only letters and numbers..
        /// </summary>
        internal static string UsernameNotValid {
            get {
                return ResourceManager.GetString("UsernameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is too long. Max 24..
        /// </summary>
        internal static string UsernameTooLong {
            get {
                return ResourceManager.GetString("UsernameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is too short. Min 3..
        /// </summary>
        internal static string UsernameTooShort {
            get {
                return ResourceManager.GetString("UsernameTooShort", resourceCulture);
            }
        }
    }
}
